version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        environment:
            HAPI_HOST: 0.0.0.0
            HAPI_PORT: 3000
            WEB3_PROVIDER: http://parity:8545
            DOCKER_SOCK: /docker.sock
        depends_on:
            - parity
        volumes:
            - /private/var/run/docker.sock:/docker.sock
    parity:
        image: ethcore/parity
        command: [--jsonrpc-interface=all, --jsonrpc-hosts=all, --pruning=fast]
        volumes:
            - ~/.parity:/root/.parity
