version: '2'
services:
    web:
        build: .
        ports:
            - "3000:3000"
        environment:
            HAPI_HOST: 0.0.0.0
            HAPI_PORT: 3000
            WEB3_PROVIDER: http://parity:8545
            DOCKER_SOCK: /docker.sock
            CONTRACT_ADDRESS: 0xf2e2e8fc20b55c28ba349afb6627f7b24e5debb1 
        depends_on:
            - parity
        command: [npm, run, dev]
        volumes:
            - /private/var/run/docker.sock:/docker.sock
            - ./index.js:/srv/app/index.js
    parity:
        image: ethcore/parity
        command: [--jsonrpc-interface=all, --jsonrpc-hosts=all, --pruning=fast, --chain=morden]
        volumes:
            - ~/.parity:/root/.parity
