version: '2'
services:
    web:
        build: .
        ports:
            - "80:3000"
        environment:
            HAPI_HOST: 0.0.0.0
            HAPI_PORT: 3000
            WEB3_PROVIDER: http://parity:8545
        depends_on:
            - parity
    parity:
        image: ethcore/parity
        command: [--jsonrpc-interface=all, --jsonrpc-hosts=all, --pruning=fast]
        volumes:
            - /srv/parity:/root/.parity
